### ISSUE TITLE
Custom buttons documentation

### ISSUE THREAD

**Issue by Raiper34** [Raiper34/ngx-simple-text-editor#14]
Create documentation for own defined custom buttons. Implementation exists.

**Comment by nricciardi** [comment]
Any updates?

Is there a way to add custom buttons with custom behavior (e.g. passing a callback)?

**Comment by Raiper34** [comment]
Hi, I have just improved the readme for now, you can look. You can also look on all the existing buttons, and how they are defined and you can inspire there https://github.com/Raiper34/ngx-simple-text-editor/blob/main/projects/ngx-simple-text-editor/src/lib/constants/editor-buttons.ts

**Comment by Raiper34** [comment]
New documentation website has been presented https://ngx-simple-text-editor.netlify.app/#/ 
Done in https://github.com/Raiper34/ngx-simple-text-editor/commit/7e21d15ee518ee793274a1dfa687b44dac5d5619
