### ISSUE TITLE
Cursor is not showing when clicking on Placeholder text

### ISSUE THREAD

**Issue by sharath-mv** [Raiper34/ngx-simple-text-editor#17]

**Comment by Raiper34** [comment]
Hi,

thanks for the issue report, but can you provide more information? Is it only on placeholder text, or in whole text area?

Thanks!

**Comment by sharath-mv** [comment]
The issue is that when clicking on top of the placeholder, it does not show the cursor in the text area. Only the text border is focusing, and I can't enter text in the text area. Clicks outside the placeholder work fine.

**Comment by Raiper34** [comment]
> The issue is that when clicking on top of the placeholder, it does not show the cursor in the text area. Only the text border is focusing, and I can't enter text in the text area. Clicks outside the placeholder work fine.

Fixed, will be part of the next release this week.

**Comment by Raiper34** [comment]
Released under v4.0.2

**Comment by Raiper34** [comment]
Additionally fixed for older Angular version in v1.4.1 v2.0.1 and v3.0.1
