### ISSUE TITLE
Buttons Language Change

### ISSUE THREAD

**Issue by TharusanK23** [Raiper34/ngx-simple-text-editor#21]
Hi,
How can change editor buttons language (Like tooltip) for localization?

**Comment by Raiper34** [comment]
Hi, 
You can create your own buttons, just inspire here https://github.com/Raiper34/ngx-simple-text-editor/blob/main/projects/ngx-simple-text-editor/src/lib/constants/editor-buttons.ts . 
You can simply copy it and paste into your code base, change titles, and use in your editor like 
```ts
import { Component } from '@angular/core';
import {EditorConfig, ST_BUTTONS} from 'ngx-simple-text-editor';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  content = '';
  config: EditorConfig = {
    placeholder: 'Type something...',
    buttons: ST_BUTTONS,
  };
}
```

**Comment by Raiper34** [comment]
I added page to documentation site https://ngx-simple-text-editor.netlify.app/#/localization
